export const FETCH_DASHBOARD_METRICS_REQUEST = 'FETCH_DASHBOARD_METRICS_REQUEST';
export const FETCH_DASHBOARD_METRICS_SUCCESS = 'FETCH_DASHBOARD_METRICS_SUCCESS';
export const FETCH_DASHBOARD_METRICS_FAILURE = 'FETCH_DASHBOARD_METRICS_FAILURE';